### ISSUE TITLE
Filter for nouns

### ISSUE THREAD

**Issue by fnielsen** [Nudin/makesense#17]
I suppose in most cases we can only match nouns. It may be an idea to restrict the number lexemes presented to nouns.

**Comment by Nudin** [comment]
I actually had the lexemes restricted to nouns in the first version, but then removed it, after discovering that we also have quite a lot of verbs and adjective as items.
What's the reason for suggesting to put it (back) in?

**Comment by fnielsen** [comment]
I think there is room for errors

```sparql
SELECT * {
  ?lexeme wikibase:lemma ?lemma ;
          ontolex:sense / wdt:P5137 ?item ;
          wikibase:lexicalCategory wd:Q24905 .
}
```

https://query.wikidata.org/#SELECT%20%2a%20%7B%0A%20%20%3Flexeme%20wikibase%3Alemma%20%3Flemma%20%3B%0A%20%20%20%20%20%20%20%20%20%20ontolex%3Asense%20%2F%20wdt%3AP5137%20%3Fitem%20%3B%0A%20%20%20%20%20%20%20%20%20%20wikibase%3AlexicalCategory%20wd%3AQ24905%20.%0A%7D

gives https://www.wikidata.org/wiki/Lexeme:L7725 (rain, verb) which in my opinion should not be linked to Q7925. But I suppose we need a discussion on Wikidata on that.

**Comment by swedebugia** [comment]
Well spottet @fnielsen. I agree these are errors when no action is mentioned on the Q-item.

**Comment by TheHarmonicRealm** [comment]
I agree that these should be filtered; there have been many occasions where I have gotten items that are clearly right for a noun with the same spelling but not the verb that shows up (and I have messed up a few times). Another thing: could items with the description "journal article" be filtered? A ton of these show up and they are not applicable to lexemes. Thanks! This is a really cool tool.

**Comment by Nudin** [comment]
I agree, that we should avoid wrong edits, but still hope to not need to limit completely on nouns, since there are also quite a few verbs with an item.
In what language do you have these issues?
For English I recently added, that verbs will be prefixed with "to" as it is custom in English anyway. So the verb "rain" would now be displayed as "to rain". I think that should make the chance of a mistake pretty low. Similar I added the articles to German words and could add other hints for other languages.

**Comment by TheHarmonicRealm** [comment]
@Nudin oh that is a very good change for English! This has only been a problem for me in English. I think that your fix probably has solved it. I'll use the tool a bit more and see. Thanks!
