### ISSUE TITLE
repopulate database - missing lexemes

### ISSUE THREAD

**Issue by so9q** [Nudin/makesense#21]
How often do you update the database? The danish lexemes curently lack senses for 1500 lexemes but only a handful show up in the tool.

**Comment by Nudin** [comment]
At the moment the database isn't updated automatically but only when I start it by hand. I did so yesterday. But for danish that didn't change much (~20 new):
The problem is that for most matches that are found the items lack a danish description. The tool only considers items that have a description since those are used as 'gloss' for the sense.
Future versions of the tool could ask the user to enter a gloss for those matches or try to auto-generate them from the P31-statement.

However I don't have time to implement this for now – see  #24. Sorry.

**Comment by Nudin** [comment]
Splitting this issue in two: #25 and #27
