### ISSUE TITLE
No match is sometimes not honored

### ISSUE THREAD

**Issue by so9q** [Nudin/makesense#22]
When I press "no match" the same match shows up a few entries later (happens in both english and danish mode)
I suggest we remove the "no match" and instead have only skip and match.

**Comment by Nudin** [comment]
This is a known bug: When you click 'no match' the browser sends that to the server which stores it in database so that it won't be presented any further. However the frontend always loads random 10 matches in advance to be able to update immediately, so it might already have recieved the match again before the negative match is sent to the server.

The frontend should remove the match also from the queue if it is present there. Shouldn't be hard to fix for someone who can write javascript, but I won't be able to do so in near future – see  #24. :(

**Comment by Nudin** [comment]
@so9q I think you where actually right, there was (another) bug in the code that caused a race condition through that a reject might not be saved. That should be fixed now.

The cleaning of the js-queue is still to do.

**Comment by Uziel302** [comment]
I am getting this error on console when clicking "no match".
"Uncaught ReferenceError: leaveEditMode is not defined
    at HTMLButtonElement.rejectAndNext (machtsinn.js:188)
rejectAndNext @ machtsinn.js:188"

**Comment by Nudin** [comment]
> I am getting this error on console when clicking "no match".
> "Uncaught ReferenceError: leaveEditMode is not defined
> at HTMLButtonElement.rejectAndNext (machtsinn.js:188)
> rejectAndNext @ machtsinn.js:188"

Sorry, Fixed! (You might need to empty cache)

**Comment by Nudin** [comment]
Should be fixed now.
