### ISSUE TITLE
Swedish (sv) is missing from the list of selectable languages

### ISSUE THREAD

**Issue by dpriskorn** [Nudin/makesense#51]

**Comment by Nudin** [comment]
It's missing because there are currently no matches to inspect. Compare with the [statistics page](https://machtsinn.toolforge.org/statistics).

**Comment by dpriskorn** [comment]
I see no sv in the middle column there. How often does this update? Is this only updated manually? How come the matcher does not find a match e.g. between https://www.wikidata.org/wiki/Q40348 and https://www.wikidata.org/wiki/Lexeme:L32073 ?

**Comment by Nudin** [comment]
The update is running weekly. 'sv' is not in the middle column because there are no matches currently.

To show a match, the tool needs a gloss for the lexem. To get the gloss MachtSinn does two things:
* Normally the description in the language of the word is used as gloss. If there are not enough matches with a description in a language there is a fallback:
* In those cases it is using the label for the Item that is used with P31.

In case of Q40348: The item has no description so this can't be used as gloss. Since there are none matches with Swedish description present the fallback is used. Q40348 has P31 set to Q15987302 – but Q15987302 has no Swedish label, therefore this fails too.
To fix that there could be either:
1. a further fallback to something else as source of the gloss or
2. one could make the gloss in the matching algorithm optional, so that the user has to insert a gloss and/or
3. add the English gloss (marked as English of course)

Option 2 and 3 should not be too hard, but I currently have no recourses for this project. Pull Request are however welcome.

User:Kristbaum has built a very similar thing as an Android app. You could try that, but it is AFAIK still in an early state:
https://play.google.com/store/apps/details?id=org.kristbaum.como

**Comment by dpriskorn** [comment]
Thanks for the thorough explanation 😃

**Comment by dpriskorn** [comment]
I will tell the Swedish community to improve and add descriptions on the items.
